spring.application.name=spring-mvc-crud

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3308/testdb?serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.thymeleaf.encoding=UTF-8
